---
urls:
  - https://www.bhphotovideo.com/c/product/1606949-REG/gigabyte_gv_n306teagle_8gd_rtx_3060_ti_eagle.html
  - https://www.bhphotovideo.com/c/product/1609756-REG/asus_ko_rtx3060ti_o8g_gaming_ko_geforce_rtx_3060.html
  - https://www.bhphotovideo.com/c/product/1607025-REG/asus_tuf_rtx3060ti_o8g_gaming_geforce_rtx_3060_ti.html
  - https://www.bhphotovideo.com/c/product/1609440-REG/pny_technologies_vcg3060t8dfxppb_geforce_rtx_3060_ti.html
  - https://www.bhphotovideo.com/c/product/1606946-REG/gigabyte_gv_n306tgamingoc_pro_8gd_rtx_3060_ti_gaming.html
  - https://www.bhphotovideo.com/c/product/1606948-REG/gigabyte_gv_n306teagle_oc_8gd_rtx_3060_ti_eagle.html
  - https://www.bhphotovideo.com/c/product/1606945-REG/gigabyte_gv_n306taorus_m_8gd_aorus_rtx_3060_ti.html
  - https://www.bhphotovideo.com/c/product/1606947-REG/gigabyte_gv_n306tgaming_oc_8gd_rtx_3060_ti_gaming.html
  - https://www.bhphotovideo.com/c/product/1610844-REG/msi_g306tv2xc_geforce_rtx_3060_ti.html
  - https://www.bhphotovideo.com/c/product/1608081-REG/zotac_zt_a30610e_10m_gaming_geforce_rtx_3060.html
  - https://www.bhphotovideo.com/c/product/1608111-REG/zotac_zt_a30610h_10m_gaming_geforce_rtx_3060.html
...
