---
refresh_interval: 2 # seconds
urls:
  - https://www.samsclub.com/p/pny-geforce-rtx3070-8gb-graphics-card/prod25090927
  - https://www.samsclub.com/p/pny-geforce-rtx3070-8gb-graphics-card/prod25090928
  - https://www.samsclub.com/p/pny-geforce-rtx3080-10gb-graphics-card/prod25090929
  - https://www.samsclub.com/p/pny-geforce-rtx3090-24gb-graphics-card/prod25090931
  - https://www.samsclub.com/p/pny-geforce-rtx3090-24gb-graphics-card/prod25090932
...
